config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  get "groups" => "groups#new"
  resources :users, only: [:edit, :update, :index]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :members
  has_many :users, through: :members
  validates :name, presence: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.body?
        last_message.body
      else
        "画像が投稿されています。"
      end
    else
      "まだメッセージはありません"
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :body, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :members
  has_many :groups, through: :members
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :set_group, only: [:edit, :update]

  def index

  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループを作成しました"
    else
      render action: :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to root_path(@group),notice: "グループを編集しました"
    else
      render :edit
    end

  end

  private

  def group_params
    params.require(:group).permit(:name, { user_ids: [] } )
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json { @messages = @messages.where('id > ?', params[:id])}
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: "メッセージが送信されました" }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where( 'name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id)

    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
=form_for @group do |f|
  -if @group.errors.any?
    .chat-group-form__errors
      %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました"
      %ul
        - @group.errors.full_messages.each do |message|
          %li= message

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, 'グループ名', class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: "グループ名を入力してください"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :user_ids, class: 'chat-group-form__label', value: 'チャットメンバーを追加'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input.chat-group-form__input{id: 'user-search-field', placeholder: '追加したいユーザー名を入力してください'}
        #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :user_ids, class: 'chat-group-form__label', value: 'チャットメンバー'
    -group.users.each do |user|
      .chat-group-form__field--right
        #chat-group-users
          #chat-group-user-22.chat-group-user.clearfix
            = f.hidden_field :user_ids, name: "group[user_ids][]", value: "#{user.id}"
            %p.chat-group-user__name
            = user.name
            %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit value: "登録する", class: "chat-group-form__action-btn"

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: "form", locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  .left
    .nickname
      .user-content
        %p.user-content__name
          = current_user.name
        %ul.menu
          %li.user-content__setting
            = link_to edit_user_path(current_user) do
              = fa_icon 'gear'
          %li.user-content__pencil
            =link_to new_group_path do
              = fa_icon 'edit'
    = render "messages/group_list"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: "form", locals: { group: @group }

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_group_list.html.haml
.groups
  - current_user.groups.each do |group|
    = link_to group_messages_path(group) do
      .group
        %p.group__group-name
          = group.name
        %p.group__group-message
          = group.show_last_message

app/views/messages/_message.html.haml
.message{ "data-message-id": "#{message.id}"}
  .upper-message
    %p.upper-message__user-name
      = message.user.name
    %p.upper-message__data
      = message.created_at.strftime('%Y/%m/%d %H:%M:%S')
  .lower-message
  - if message.body.present?
    %p.lower-message__data
      = message.body
  = image_tag message.image.url if message.image.present?

app/views/messages/index.html.haml
.wrapper
  .left
    .nickname
      .user-content
        %p.user-content__name
          = current_user.name
        %ul.menu
          %li.user-content__setting
            = link_to edit_user_path(current_user) do
              = fa_icon 'gear'
          %li.user-content__pencil
            =link_to new_group_path do
              = fa_icon 'edit'
    = render "group_list"
  .right
    .header
      .left-header
        %p.left-header__title
          = @group.name
        %ul.members
          %li.members__list Member :
          - @group.users.each do |user|
            %li.members__list
              = user.name

      .edit
        = link_to 'Edit', edit_group_path(@group)
    .messages
      = render @messages

    .footer
      = form_for [@group, @message], html: {class: 'message-form' } do |f|
        = f.text_field :body, class: 'message-form__message-content', placeholder: 'type a message'
        = f.label :image do
          = f.file_field :image, class: 'message-form__icon'
          = fa_icon 'image'
        = f.submit 'Send', class: 'message-form__button'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name, "name"
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'